Repository SEP-proj/back-end, pull requests merged in 2023-09, with the labels that each got.

#3 POST CUD 구현
  src/main/java/com/septeam/metatraining/post/command/application/dto/postDTO.java
  src/main/java/com/septeam/metatraining/post/command/application/service/CreatedPostService.java
  src/main/java/com/septeam/metatraining/post/command/application/service/DeletePostService.java
  src/main/java/com/septeam/metatraining/post/command/application/service/UpdatePostService.java
  src/main/java/com/septeam/metatraining/post/command/domain/aggregate/entity/Post.java
  src/main/java/com/septeam/metatraining/post/command/domain/aggregate/entity/enumType/CategoryEnum.java
  src/main/java/com/septeam/metatraining/post/command/domain/aggregate/vo/MemberVO.java
  src/main/java/com/septeam/metatraining/post/command/domain/repository/PostRepository.java
  src/test/java/com/septeam/metatraining/post/command/service/PostCRUDTests.java
Labels: 🌟Feature

#11 [#10]Feat : Post controller 작성
  build.gradle
  src/main/java/com/septeam/metatraining/common/annotation/CustomCommonApiResponse.java
  src/main/java/com/septeam/metatraining/common/response/ApiRequest.java
  src/main/java/com/septeam/metatraining/common/response/ApiResponse.java
  src/main/java/com/septeam/metatraining/configuration/SecurityConfiguration.java
  src/main/java/com/septeam/metatraining/configuration/SwaggerConfiguration.java
  src/main/java/com/septeam/metatraining/post/command/application/controller/PostController.java
  src/main/java/com/septeam/metatraining/post/command/application/dto/PostDTO.java
  src/main/java/com/septeam/metatraining/post/command/application/dto/TitleDTO.java
  src/main/java/com/septeam/metatraining/post/command/application/service/CreatedPostService.java
  src/main/java/com/septeam/metatraining/post/command/application/service/UpdatePostService.java
  src/main/java/com/septeam/metatraining/post/command/domain/aggregate/entity/Post.java
  src/test/java/com/septeam/metatraining/post/command/service/PostCRUDTests.java
Labels: 📬API, 🌟Feature

#5 [Closes #4]Feat : Init Swagger
  build.gradle
  src/main/java/com/septeam/metatraining/configuration/SwaggerConfiguration.java
Labels: 📬API, 📜Docs, 🌟Feature

#14 [#12] AI와 통신을 위한 controller method추가
  src/main/java/com/septeam/metatraining/configuration/WebClientConfiguration.java
  src/main/java/com/septeam/metatraining/post/command/application/controller/PostController.java
  src/main/java/com/septeam/metatraining/post/command/application/dto/ai/subject/CategoryDTO.java
  src/main/java/com/septeam/metatraining/post/command/application/dto/ai/subject/GetSubjectDTO.java
  src/main/java/com/septeam/metatraining/post/command/application/service/AIApisService.java
Labels: 📬API, 🌟Feature

#16 [#15] CORS 커스텀 설정
  src/main/java/com/septeam/metatraining/configuration/SecurityConfiguration.java
  src/main/java/com/septeam/metatraining/post/command/application/controller/PostController.java
  src/main/java/com/septeam/metatraining/post/command/application/service/AIApisService.java
Labels: 🏗️Refactoring

#18 [#12] API와 통신을 위한 controller method 추가 및 서비스 메소드 추가
  src/main/java/com/septeam/metatraining/post/command/application/controller/PostController.java
  src/main/java/com/septeam/metatraining/post/command/application/service/AIApisService.java
Labels: 📬API, 🌟Feature

#22 Feat : Oauth2를 사용한 login 및 회원 등록 기능 구현
  build.gradle
  src/main/java/com/septeam/metatraining/configuration/SecurityConfiguration.java
  src/main/java/com/septeam/metatraining/configuration/WebClientConfiguration.java
  src/main/java/com/septeam/metatraining/member/command/application/dto/CreateMemberDTO.java
  src/main/java/com/septeam/metatraining/member/command/application/dto/UpdateMemberDTO.java
  src/main/java/com/septeam/metatraining/member/command/application/service/CreateMemberService.java
  src/main/java/com/septeam/metatraining/member/command/application/service/UpdateMemberService.java
  src/main/java/com/septeam/metatraining/member/command/domain/aggregate/entity/Member.java
  src/main/java/com/septeam/metatraining/member/command/domain/aggregate/entity/enumtype/Role.java
  src/main/java/com/septeam/metatraining/member/command/domain/repository/MemberRepository.java
  src/main/java/com/septeam/metatraining/member/command/domain/service/MemberService.java
  src/main/java/com/septeam/metatraining/member/query/application/dto/FindMemberDTO.java
  src/main/java/com/septeam/metatraining/member/query/application/service/FindMemberService.java
  src/main/java/com/septeam/metatraining/member/query/domain/repository/MemberMapper.java
  src/main/java/com/septeam/metatraining/security/Principal/UserPrincipal.java
  src/main/java/com/septeam/metatraining/security/command/application/service/CustomOAuth2UserService.java
  src/main/java/com/septeam/metatraining/security/command/domain/provider/Google.java
  src/main/java/com/septeam/metatraining/security/command/domain/provider/OAuth2UserInfo.java
  src/main/java/com/septeam/metatraining/security/command/domain/provider/OAuth2UserInfoFactory.java
  src/main/resources/mapper/member/MemberMapper.xml
  src/test/java/com/septeam/metatraining/member/MemberCommandServiceTest.java
  src/test/java/com/septeam/metatraining/member/MemberQueryServiceTest.java
Labels: 🌟Feature

#24 [#17] 글 조회 서비스 기능 구현
  build.gradle
  src/main/java/com/septeam/metatraining/post/query/application/service/FindPostService.java
  src/main/java/com/septeam/metatraining/post/query/domain/repository/PostMapper.java
  src/main/resources/config/mybatis-config.xml
  src/main/resources/mapper/post/PostMapper.xml
Labels: 🌟Feature

#28 [#25] 글 조회 기능 Controller 구현
  src/main/java/com/septeam/metatraining/post/command/application/controller/PostController.java
  src/main/java/com/septeam/metatraining/post/command/application/service/AIApisService.java
  src/main/java/com/septeam/metatraining/post/command/application/service/UpdatePostService.java
  src/main/java/com/septeam/metatraining/post/query/application/controller/FindPostController.java
  src/test/java/com/septeam/metatraining/post/command/service/PostCRUDTests.java
  src/test/java/com/septeam/metatraining/post/query/service/PostReadTests.java
Labels: 📬API, 🌟Feature

#29 [Closes #27] Feat : Security Controller Advice 추가 및 Test 추가
  src/main/java/com/septeam/metatraining/common/advice/AuthControllerAdvice.java
  src/main/java/com/septeam/metatraining/common/response/error/ErrorResponse.java
  src/main/java/com/septeam/metatraining/common/response/error/ErrorResponseBody.java
  src/main/java/com/septeam/metatraining/configuration/SecurityConfiguration.java
  src/main/java/com/septeam/metatraining/configuration/TomcatWebConfiguration.java
  src/test/java/com/septeam/metatraining/security/IssueTokenServiceTest.java
  src/test/java/com/septeam/metatraining/security/TokenServiceTest.java
Labels: 🌟Feature

#32 [#25] 글 조회 서비스 기능 controller 구현
  src/main/java/com/septeam/metatraining/post/command/domain/aggregate/entity/Post.java
  src/main/java/com/septeam/metatraining/post/query/application/controller/FindPostController.java
  src/main/java/com/septeam/metatraining/post/query/application/dto/FindPostDTO.java
  src/main/java/com/septeam/metatraining/post/query/application/service/FindPostService.java
  src/main/java/com/septeam/metatraining/post/query/domain/repository/PostMapper.java
  src/main/resources/mapper/post/PostMapper.xml
  src/test/java/com/septeam/metatraining/post/command/service/PostCRUDTests.java
  src/test/java/com/septeam/metatraining/post/query/service/PostReadTests.java
Labels: 📬API, 🌟Feature, ✅Test

#34 [Closes #33] API요청(post) controller refactoring
  src/main/java/com/septeam/metatraining/configuration/WebClientConfiguration.java
  src/main/java/com/septeam/metatraining/post/command/application/controller/PostController.java
  src/main/java/com/septeam/metatraining/post/command/application/service/AIApisService.java
Labels: 📬API, 🏗️Refactoring

#36 [Closes #35] refactoring controller
  src/main/java/com/septeam/metatraining/post/command/application/controller/PostController.java
  src/main/java/com/septeam/metatraining/post/command/application/service/AIApisService.java
  src/main/java/com/septeam/metatraining/post/command/application/service/CreatedPostService.java
Labels: 🏗️Refactoring
